model: tf_efficientnet_b3_ns
batch_size : 32
image_size : 512
seed : 42
pretrained : true
num_workers : 4
pin_memory : true

train_dir  : /content/train
test_dir : /content/test
train_file_path : /content/train_colab.csv
epochs: 10
in_channels: 3
folds:
      - 0
      - 1
      - 2


scheduler_name: CosineAnnealingWarmRestarts
T_0: 5
T_max: 5
T_mult: 1
min_lr: 1e-7
max_lr: 1e-4
lr: 1e-5
weight_decay: 1e-6
target_size : 100
device : cuda
model_dir : /content/baseline_tf_efficientnet_b0_ns
n_fold: 5
