model: resnet34
batch_size : 32
image_size : 512
seed : 42
pretrained : true
num_workers : 4
pin_memory : true

train_dir  : ../input/cultivar-identification-jpeg/train_img
test_dir : ../input/cultivar-identification-jpeg/test_img
train_file_path : ./train.csv
epochs: 10
in_channels: 3
folds:
      - 0
      - 1
      - 2
      - 3
      - 4

scheduler_name: CosineAnnealingWarmRestarts
T_0: 5
T_max: 5
T_mult: 1
min_lr: 1e-7
max_lr: 1e-4
lr: 2e-4
weight_decay: 1e-6
target_size : 100
device : cuda
model_dir : ./resnet34
n_fold: 5
