model: convnext_base_384_in22ft1k
batch_size : 8
image_size : 512
seed : 42
pretrained : true
num_workers : 4
pin_memory : true

train_dir  : /content/train/
test_dir : /content/test
train_file_path : /content/train_cultivar_mapping.csv
label_encoder_path : /content/classes.npy
epochs: 10
in_channels: 3
folds:
      - 0
      - 1
      - 2
      - 3
      - 4


scheduler_name: CosineAnnealingWarmRestarts
T_0: 5
T_max: 5
T_mult: 1
min_lr: 1e-7
max_lr: 1e-4
lr: 2e-4
weight_decay: 1e-6
target_size : 100
device : cuda
model_dir : /content/convnext_base
n_fold: 5
triplet_kernel_size : 7
pool_p : 3
triplet : false
