model: tf_efficientnet_b6_ns
batch_size: 8
image_size: 528
seed: 42
pretrained: true
num_workers: 20
pin_memory: true

train_dir: /home/mithil/PycharmProjects/Cultivar_FGVC9/data/archive/train/
test_dir: /home/mithil/PycharmProjects/Cultivar_FGVC9/data/archive/test/
train_file_path: /home/mithil/PycharmProjects/Cultivar_FGVC9/data/archive/train_cultivar_mapping.csv
label_encoder_path: /home/mithil/PycharmProjects/Cultivar_FGVC9/data/archive/classes.npy
epochs: 10
in_channels: 3
folds:

  - 2




scheduler_name: CosineAnnealingWarmRestarts
T_0: 5
T_max: 5
T_mult: 1
min_lr: 1e-7
max_lr: 1e-4
lr: 2e-4
weight_decay: 1e-6
target_size: 100
device: cuda
model_dir: /home/mithil/PycharmProjects/Cultivar_FGVC9/models/tf_efficientnet_b6_ns
n_fold: 5
triplet: false