model: tf_efficientnet_b3_ns
batch_size: 16
image_size: 512
seed: 42
pretrained: false
num_workers: 0
pin_memory: true

train_dir: /home/mithil/PycharmProjects/Cultivar_FGVC9/data/archive/train
train_file_path: /home/mithil/PycharmProjects/Cultivar_FGVC9/data/archive/train_cultivar_mapping.csv
label_encoder_path: /home/mithil/PycharmProjects/Cultivar_FGVC9/data/archive/classes.npy
in_channels: 3

target_size: 100
device: cuda
model_dir: /home/mithil/PycharmProjects/Cultivar_FGVC9/models/effneb3_mixup_20
n_fold: 5
oof_file_path: /home/mithil/PycharmProjects/Cultivar_FGVC9/oof/tf_efficientnet_b3_ns_mixup_20.csv
oof_probablity_path : /home/mithil/PycharmProjects/Cultivar_FGVC9/oof/tf_efficientnet_b3_ns_mixup_20_probablity.npy