model: swinv2_base_window16_256
batch_size: 16
image_size: 256
seed: 42
pretrained: false
num_workers: 8
pin_memory: true
model_path: /Cultivar_FGVC9/models/swin_v2_base_256
test_dir: /Cultivar_FGVC9/data/archive/test
train_file_path: /Cultivar_FGVC9/data/archive/train_cultivar_mapping.csv

sample_sub_file: /Cultivar_FGVC9/data/archive/sample_submission.csv
submission_file: /Cultivar_FGVC9/submissions/tta/swinv2_base_window16_256_submission.csv
probablity_file: /Cultivar_FGVC9/submissions/tta/swinv2_base_window16_256_probablity.npy
target_size: 100
device: cuda
in_channels: 3
n_folds: 5
