model: tf_efficientnet_b3_ns
batch_size: 16
image_size: 1024
seed: 42
pretrained: false
num_workers: 4
pin_memory: true
model_path: /home/mithil/PycharmProjects/Cultivar_FGVC9/models/effnetb3_cutmix_30_epoch
test_dir: /home/mithil/PycharmProjects/Cultivar_FGVC9/data/archive/test
train_file_path: /home/mithil/PycharmProjects/Cultivar_FGVC9/data/archive/train_cultivar_mapping.csv

sample_sub_file: /home/mithil/PycharmProjects/Cultivar_FGVC9/data/archive/sample_submission.csv
submission_file: /home/mithil/PycharmProjects/Cultivar_FGVC9/submissions/tta/tf_efficientnet_b3_ns_cutmix_submission.csv
probablity_file: /home/mithil/PycharmProjects/Cultivar_FGVC9/submissions/tta/tf_efficientnet_b5_ns_cutmix_probablity.npy
target_size: 100
device: cuda
in_channels: 3
n_folds: 5