model: dm_nfnet_f0
batch_size: 16
image_size: 512
seed: 42
pretrained: false
num_workers: 4
pin_memory: true

train_dir: /content/train/
test_dir: /content/test
train_file_path: /content/train_cultivar_mapping.csv
label_encoder_path: /content/classes.npy
epochs: 25
in_channels: 3
folds:
  - 0
  - 1
  - 2
  - 3
  - 4


scheduler_name: CosineAnnealingWarmRestarts
optimizer: Adam
T_0: 5
T_max: 5
T_mult: 1
min_lr: 1e-7
max_lr: 1e-3
lr: 3e-4
weight_decay: 1e-6
target_size: 100
device: cuda
model_dir: /content/tf_efficientnet_b4_ns_mixup_betteraug
n_fold: 5
mixup: False
cutmix: True
cutmix_alpha: 1.0
mixup_alpha: 1.0
triplet_kernel_size: 7
pool_p: 3
triplet: False
pct_start: 0.2
div_factor: 1.0e+3
final_div_factor: 1.0e+3
snapmix: False
snapmix_alpha: 1.0
n_aug: 3