model: tf_efficientnet_b3_ns
batch_size: 24
image_size: 512
seed: 42
pretrained: false
num_workers: 4
pin_memory: true
model_path: /home/mithil/PycharmProjects/Cultivar_FGVC9/models/effnetb3_moreaugs_30
test_dir: /home/mithil/PycharmProjects/Cultivar_FGVC9/data/archive/test
train_file_path: /home/mithil/PycharmProjects/Cultivar_FGVC9/data/archive/train_cultivar_mapping.csv

sample_sub_file: /home/mithil/PycharmProjects/Cultivar_FGVC9/data/archive/sample_submission.csv
submission_file: /home/mithil/PycharmProjects/Cultivar_FGVC9/submissions/tta/tf_efficientnet_b3_AUGS_ns_mixup_more_epoch_more_tta_submission.csv
probablity_file: /home/mithil/PycharmProjects/Cultivar_FGVC9/submissions/tta/tf_efficientnet_b3_AUGS_ns_mixup_more_epoch_more_tta_probablity.npy
target_size: 100
device: cuda
in_channels: 3
n_folds: 5